project:
  type: website
  output-dir: docs

website:
  title: "Tadeu Eder da Silva, PhD"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: videos.qmd
        text: Videos
    right:
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=RsZ9F8gAAAAJ&hl=en
      - icon: linkedin
        href: https://linkedin.com/in/tadeu-eder-da-silva-78b679181/
      - icon: github
        href: https://github.com/TEDS-91

format:
  html:
    theme: cosmo
    css: styles.css




