project:
  type: website

website:
  title: "Tadeu Eder da Silva"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sobre
      - text: Posts
        menu:
          - posts/post1.qmd
          - posts/post2.qmd

format:
  html:
    theme: cosmo
    css: styles.css




