project:
  type: website

website:
  title: "Tadeu Eder da Silva, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: about.qmd
        text: About
      - text: Posts
        menu:
          - posts/post1.qmd
          - posts/post2.qmd

format:
  html:
    theme: cosmo
    css: styles.css




